# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RACTestSecond' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RACTestSecond
  pod 'ReactiveObjC'

  target 'RACTestSecondTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACTestSecondUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
